### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by GrafHammerman** [Parik27/DragonFF#178] opened 2022-10-07 19:45 UTC
This error appear when i try to activate the addon in Blender 2.79b

![image](https://user-images.githubusercontent.com/33943178/194641550-a99f51a9-8ec7-4bf4-9a02-8ed2b9875793.png)

**Comment by Parik27** [comment] 2022-10-07 20:07
Duplicate of #161 

You can't use the add-on on a 5 year old version of Blender.

**Closed by Parik27** 2022-10-07 20:07 UTC
